In [ ]:
import pandas as pd
df = pd.DataFrame(
    {"AAA": [4, 5, 6, 7], "BBB": [10, 20, 30, 40], "CCC": [100, 50, -30, -50]}
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

# if-then

In [5]:
df.loc[df.AAA >= 5, "BBB"] = -1
df

   AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

In [6]:
df.loc[df.AAA < 5, ["BBB", "CCC"]] = 2000
df

   AAA   BBB   CCC
0    4  2000  2000
1    5    -1    50
2    6    -1   -30
3    7    -1   -50

# Splitting

In [12]:
df = pd.DataFrame(
    {"AAA": [4, 5, 6, 7], "BBB": [10, 20, 30, 40], "CCC": [100, 50, -30, -50]}
)
df

   AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [13]:
df[df.AAA <= 5]

   AAA  BBB  CCC
0    4   10  100
1    5   20   50

In [15]:
df[df.AAA > 5]

   AAA  BBB  CCC
2    6   30  -30
3    7   40  -50

In [19]:
df.loc[(df["BBB"] < 25) & (df["CCC"] >= 50), "AAA"]

0    4
1    5
Name: AAA, dtype: int64

In [24]:
df.loc[(df["BBB"] > 25) | (df["CCC"] >= 75), "AAA"]=0.1
df

   AAA  BBB  CCC
0  0.1   10  100
1  5.0   20   50
2  0.1   30  -30
3  0.1   40  -50

#Creating example data

In [29]:


import itertools

def expand_grid(data_dict):
    rows = itertools.product(*data_dict.values())
    return pd.DataFrame.from_records(rows, columns=data_dict.keys())


df = expand_grid(
    {"height": [60, 70,80], "weight": [60, 70, 80, 90], "sex": ["Male", "Female"]}
)

df

    height  weight     sex
0       60      60    Male
1       60      60  Female
2       60      70    Male
3       60      70  Female
4       60      80    Male
5       60      80  Female
6       60      90    Male
7       60      90  Female
8       70      60    Male
9       70      60  Female
10      70      70    Male
11      70      70  Female
12      70      80    Male
13      70      80  Female
14      70      90    Male
15      70      90  Female
16      80      60    Male
17      80      60  Female
18      80      70    Male
19      80      70  Female
20      80      80    Male
21      80      80  Female
22      80      90    Male
23      80      90  Female

In [30]:
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
df=pd.DataFrame(iris)
df
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

#Data frame from Dictionary

In [35]:
import pandas as pd

# Python dict object
student_dict = {'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.10, 77.80]}
print(student_dict)

# Create DataFrame from dict
student_df = pd.DataFrame(student_dict)
print(student_df)

{'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.1, 77.8]}
  Name  Age  Marks
0  Joe   20   85.1
1  Nat   21   77.8

#Display

In [38]:
url="https://raw.githubusercontent.com/milaan9/10_Python_Pandas_Module/main/automobile_data.csv"
df=pd.read_csv(url, on_bad_lines='skip')
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

[Pandas learning](https://github.com/milaan9/10_Python_Pandas_Module)